### PR TITLE
CJ-1-Spawn crates in randomised but safe locations

### LINKED ISSUE #1: Spawn crates in randomised but safe locations
Come up with a script or EDEN solution that spawn crates in randomised but safe locations.

### LINKED ISSUE #3: Create map markers of the spawned crates
Create map markers of the spawned crates (non-dynamic) only visible to insurgents so they can plan their ambushes.

### PR DESCRIPTION
**Pull request by milivojm**
Resolves #1. Resolves #3.

### CODE REVIEW

**Comment by milivojm** [comment]
Limitations:

- Crates need to be spawned in the open due to limitations of Arma markers (they are 2D). I've tried doing it "in the building" but crates magically disappear.
- Instead of map markers for cache locations I've placed tasks which are more suited for multiplayer nature. There is a neat BI function that handles notifications for sides, groups and is part of [Arma 3 Tasks Framework](https://community.bistudio.com/wiki/Arma_3_Task_Framework_Tutorial).

**Comment by JamesTheClarke** [comment]
is it possible to cheat the invisible map markers by adjusting their Z values? could that address the height at which spawns the crates?

**Comment by milivojm** [comment]
We can use "game logic" entities instead of markers. They have 3d positions.

**Comment by JamesTheClarke** [comment]
If that works it would be great as it offers more placement options and forces players to investigate rooms. Once they realise crates only spawn outside it could affect gameplay and replayability.

**Comment by milivojm** [comment]
I have removed markers and placed RHS crates with simulation disabled, hidden. Instead of spawning we will just show randomly selected cache in the 250m around the objective. This makes mission editing easier since you don't need to pay attention to correct naming of the placeholders.

**Pull request merged**
